# -*- coding: utf-8 -*-
"""AFM-Filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JLa5EWORMhKuO4YkxiMjrk_2IiipcvH
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import cv2

def extract_afm_values_and_rms(image_path, min_value=0.0, max_value=6.5):
    # Load the image
    img = Image.open('/content/AFM-MASK.png')
    img_array = np.array(img)

    # Convert to grayscale
    if len(img_array.shape) == 3:
        # Convert RGB to grayscale using luminance formula
        gray_img = cv2.cvtColor(img_array, cv2.COLOR_RGB2GRAY)
    else:
        gray_img = img_array

    # Normalize grayscale values to 0-1 range
    normalized_gray = gray_img.astype(float) / 255.0

    # Map grayscale values to the measurement scale
    values = min_value + (max_value - min_value) * normalized_gray

    # Calculate RMS (Root Mean Square)
    rms_value = np.sqrt(np.mean(values**2))

    return rms_value, values, img_array

def plot_results(original_img, values_array, rms_value, min_val, max_val,
                coverage_mask=None, threshold=None):

    if coverage_mask is not None:
        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 5))
    else:
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Plot original image
    ax1.imshow(original_img, cmap='hot')
    ax1.set_title('Original AFM Image')
    ax1.axis('off')

    # Plot extracted values
    im = ax2.imshow(values_array, cmap='hot', vmin=min_val, vmax=max_val)
    ax2.set_title(f'Extracted Values\nRMS = {rms_value:.3f} nm')
    ax2.axis('off')

    # Add colorbar
    plt.colorbar(im, ax=ax2, label='Height (nm)')

    # Plot coverage mask if provided
    if coverage_mask is not None:
        ax3.imshow(coverage_mask, cmap='RdYlBu_r', alpha=0.8)
        ax3.set_title(f'Surface Coverage\n(Above {threshold:.2f} nm)')
        ax3.axis('off')

        # Add text overlay showing coverage percentage
        coverage_pct = np.sum(coverage_mask) / coverage_mask.size * 100
        ax3.text(0.02, 0.98, f'{coverage_pct:.1f}% coverage',
                transform=ax3.transAxes, fontsize=12, fontweight='bold',
                verticalalignment='top', bbox=dict(boxstyle='round',
                facecolor='white', alpha=0.8))

    plt.tight_layout()
    plt.show()

    return fig

def calculate_surface_coverage(values_array, height_threshold):
    # Create binary mask where True = above threshold
    above_threshold = values_array > height_threshold

    # Count pixels above threshold
    pixels_above_threshold = np.sum(above_threshold)
    total_pixels = values_array.size

    # Calculate surface coverage as fraction
    surface_coverage = pixels_above_threshold / total_pixels

    # Calculate coverage percentage
    coverage_percentage = surface_coverage * 100

    coverage_stats = {
        'surface_coverage_fraction': surface_coverage,
        'surface_coverage_percentage': coverage_percentage,
        'pixels_above_threshold': pixels_above_threshold,
        'total_pixels': total_pixels,
        'threshold_used': height_threshold
    }

    return coverage_stats, above_threshold

def calculate_statistics(values_array):
    """
    Calculate additional statistics for the AFM data.
    """
    stats = {
        'mean': np.mean(values_array),
        'std': np.std(values_array),
        'rms': np.sqrt(np.mean(values_array**2)),
        'min': np.min(values_array),
        'max': np.max(values_array),
        'range': np.max(values_array) - np.min(values_array)
    }
    return stats



# Replace with your image path
image_path = "afm_image.jpg"  # Change this to your image file path

# Define the scale range (adjust based on your colorbar)
min_height = 0.0   # nm (darkest color)
max_height = 5.0   # nm (brightest color)

# Define height threshold for surface coverage analysis
height_threshold = 2.2 # nm (adjust based on your analysis needs)

# Extract values and calculate RMS
rms, values, original = extract_afm_values_and_rms(
            image_path, min_height, max_height)

# Calculate additional statistics
stats = calculate_statistics(values)

# Calculate surface coverage
coverage_stats, coverage_mask = calculate_surface_coverage(values, height_threshold)

# Print results
print(f"AFM Image Analysis Results:")
print(f"RMS Height: {rms:.3f} nm")
print(f"Mean Height: {stats['mean']:.3f} nm")
print(f"Standard Deviation: {stats['std']:.3f} nm")
print(f"Height Range: {stats['min']:.3f} - {stats['max']:.3f} nm")
print(f"Total Range: {stats['range']:.3f} nm")
print(f"\nSurface Coverage Analysis:")
print(f"Height Threshold: {coverage_stats['threshold_used']:.3f} nm")
print(f"Surface Coverage: {coverage_stats['surface_coverage_percentage']:.2f}%")
print(f"Pixels Above Threshold: {coverage_stats['pixels_above_threshold']} / {coverage_stats['total_pixels']}")

# Plot results including coverage mask
plot_results(original, values, rms, min_height, max_height,
              coverage_mask, height_threshold)