# -*- coding: utf-8 -*-
"""CirclePlacement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvJWVfVbLDtxYR0Fw7Tn-Lf-LgFaIf8_
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import pdist, squareform
from scipy.optimize import minimize_scalar
from sklearn.cluster import DBSCAN
import cv2
from PIL import Image

class CircleCoverageAnalyzer:
    def __init__(self, image_path=None, image_array=None):

        self.image = np.array(Image.open(image_path))

        self.red_pixels = None
        self.circle_centers = None
        self.circle_radius = None
        self.overlap_threshold = None

    def detect_red_regions(self, red_threshold=150, green_threshold=100, blue_threshold=100):

        if len(self.image.shape) == 3:
            # Color image
            red_mask = (self.image[:,:,0] > red_threshold) & \
                      (self.image[:,:,1] < green_threshold) & \
                      (self.image[:,:,2] < blue_threshold)
        else:
            # Grayscale - assume higher values are red regions
            red_mask = self.image > red_threshold

        # Get coordinates of red pixels
        red_coords = np.column_stack(np.where(red_mask))
        self.red_pixels = red_coords

        coverage = np.sum(red_mask) / (self.image.shape[0] * self.image.shape[1])
        print(f"Red region coverage: {coverage:.1%}")

        return red_coords

    def place_circles_greedy(self, circle_radius=1, overlap_threshold=0.3):

        self.circle_radius = circle_radius
        self.overlap_threshold = overlap_threshold

        if self.red_pixels is None:
            self.detect_red_regions()

        uncovered_pixels = self.red_pixels.copy()
        circles = []

        while len(uncovered_pixels) > 0:
            # Find the best position for the next circle
            best_center = None
            best_coverage = 0

            # Sample potential centers from uncovered pixels
            sample_size = min(100, len(uncovered_pixels))
            sample_indices = np.random.choice(len(uncovered_pixels), sample_size, replace=False)
            candidate_centers = uncovered_pixels[sample_indices]

            for center in candidate_centers:
                # Count how many uncovered pixels this circle would cover
                distances = np.linalg.norm(uncovered_pixels - center, axis=1)
                coverage_count = np.sum(distances <= circle_radius)

                if coverage_count > best_coverage:
                    best_coverage = coverage_count
                    best_center = center

            if best_center is None:
                break

            # Check overlap constraint with existing circles
            valid_placement = True
            for existing_center in circles:
                dist = np.linalg.norm(best_center - existing_center)
                overlap_dist = 2 * circle_radius - dist
                max_overlap = overlap_threshold * np.pi * circle_radius**2

                if overlap_dist > 0:
                    # Calculate actual overlap area (approximate)
                    if dist < 2 * circle_radius:
                        # Simplified overlap calculation
                        relative_overlap = overlap_dist / (2 * circle_radius)
                        if relative_overlap > overlap_threshold:
                            valid_placement = False
                            break

            if valid_placement:
                circles.append(best_center)
                # Remove covered pixels
                distances = np.linalg.norm(uncovered_pixels - best_center, axis=1)
                covered_mask = distances <= circle_radius
                uncovered_pixels = uncovered_pixels[~covered_mask]
            else:
                # Remove this candidate to avoid infinite loop
                mask = np.any(uncovered_pixels != best_center, axis=1)
                uncovered_pixels = uncovered_pixels[mask]

        self.circle_centers = np.array(circles)
        print(f"Placed {len(circles)} circles with radius {circle_radius}")
        return self.circle_centers

    def _periodic_distance(self, point1, point2):

        height, width = self.image.shape[:2]

        # Calculate differences in each dimension
        dy = abs(point1[0] - point2[0])
        dx = abs(point1[1] - point2[1])

        # Apply periodic boundary conditions
        dy = min(dy, height - dy)
        dx = min(dx, width - dx)

        return np.sqrt(dx**2 + dy**2)

    def _periodic_distances_vectorized(self, centers):

        height, width = self.image.shape[:2]
        n = len(centers)

        # Create arrays for all pairs
        i_indices, j_indices = np.triu_indices(n, k=1)
        points1 = centers[i_indices]
        points2 = centers[j_indices]

        # Calculate differences
        dy = np.abs(points1[:, 0] - points2[:, 0])
        dx = np.abs(points1[:, 1] - points2[:, 1])

        # Apply periodic boundary conditions
        dy = np.minimum(dy, height - dy)
        dx = np.minimum(dx, width - dx)

        # Calculate distances
        distances = np.sqrt(dx**2 + dy**2)

        return distances

    def visualize_coverage(self, figsize=(12, 5)):

        fig, axes = plt.subplots(1, 2, figsize=figsize)

        # Original image
        axes[0].imshow(self.image)
        axes[0].set_title('Original Image')
        axes[0].axis('off')

        # Circle coverage
        axes[1].imshow(self.image)

        if self.circle_centers is not None:
            for center in self.circle_centers:
                circle = plt.Circle((center[1], center[0]), self.circle_radius,
                                  fill=False, color='yellow', linewidth=1.5, alpha=0.7)
                axes[1].add_patch(circle)

        axes[1].set_title(f'Circle Coverage ({len(self.circle_centers)} circles)')
        axes[1].axis('off')

        plt.tight_layout()
        plt.show()

        # Calculate coverage statistics
        if self.circle_centers is not None:
            total_circle_area = len(self.circle_centers) * np.pi * self.circle_radius**2
            image_area = self.image.shape[0] * self.image.shape[1]
            circle_coverage = total_circle_area / image_area

            print(f"Circle coverage: {circle_coverage:.1%}")
            print(f"Average circle density: {len(self.circle_centers)/image_area*10000:.2f} circles per 10k pixels")



#Replace AFM-FILTER.png with thresholded AFM image
analyzer = CircleCoverageAnalyzer(image_path='/content/AFM-FILTER.png')
analyzer.place_circles_greedy(circle_radius=8, overlap_threshold=0.2)
analyzer.visualize_coverage()